services:
  yakyn-mini-app-local:
    container_name: yakyn-mini-app-local
    build:
      context: ../..
      dockerfile: .deploy/_shared/Dockerfile
    ports:
      - "10310:5173"
    restart: unless-stopped
    volumes:
      - ../../:/app
      - /app/node_modules
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development

networks:
  default:
    external: true
    name: yakyn_network
